<a href="https://colab.research.google.com/github/NubasVAdidas/potapov_1iis_41/blob/%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%B8%D0%B5-%D1%8F%D0%B7%D1%8B%D0%BA%D0%BE%D0%B2%D1%8B%D0%B5-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8/notebooks/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ЗАДАНИЕ 1**

In [26]:
import pandas as pd
titanic = pd.read_csv('train.csv')
display(titanic.head(10))
print(f"\n\n{60*'*='}\n\n")
display(titanic.tail())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

**ЗАДАНИЕ 2**

In [27]:
display(titanic.info())
print(f"\n\n{60*'*='}\n\n")
display(titanic.describe())
print(f"\n\n{60*'*='}\n\n")
display(titanic.describe(include=['object']))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

None

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

**ЗАДАНИЕ 3**

In [45]:
emb = titanic["Embarked"].head()
emb.index = ["one", "two", "three", "four", "five"]
display(emb)
print(f"\n\n{60*'*='}\n\n")
display(emb.loc["one"])
print(f"\n\n{60*'*='}\n\n")
display(emb.iloc[4]) #five

one      S
two      C
three    S
four     S
five     S
Name: Embarked, dtype: object

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

'S'

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

'S'

**ЗАДАНИЕ 4**

In [50]:
age_mean = titanic.Age.mean()
print(f"Средний возраст пассажиров: {age_mean:.2f}")
print(f"\n\n{60*'*='}\n\n")
fare_min = titanic.Fare.min()
fare_max = titanic.Fare.max()
print(f"Максимальная цена билета: {fare_max:.2f}\nМинимальная цена билета: {fare_min}")
print(f"\n\n{60*'*='}\n\n")
age_std = titanic.Age.std()
print(f"Среднее отклонение возраста {age_std: .2f}")

Средний возраст пассажиров: 29.70


*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=


Максимальная цена билета: 512.33
Минимальная цена билета: 0.0


*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=


Среднее отклонение возраста 14.53

**ЗАДАНИЕ 5**

In [58]:
age_sort = titanic[titanic.Age > 30]
display(age_sort)
print(f"\n\n{60*'*='}\n\n")
fare_sort = titanic[titanic.Fare > titanic.Fare.mean()]
print(f"Средняя цена билета: {titanic.Fare.mean():.2f}")
display(fare_sort)
print(f"\n\n{60*'*='}\n\n")
rich_woman = titanic[(titanic.Pclass == 1) & (titanic.Sex == "female")]
display(rich_woman)
age_rw = rich_woman.Age.mean()
print(f"Средний возраст женщин в первом классе: {age_rw:.2f}")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=


Средняя цена билета: 32.20

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

Средний возраст женщин в первом классе: 34.61

**ЗАДАНИЕ 6**

In [60]:
survived_people = titanic[(titanic.Survived == 1) & (titanic.Age < 18)]
display(survived_people)
sp_fare_mean = survived_people.Fare.mean()
sp_count = survived_people.PassengerId.count()
print(f"Средняя стоимость билета выживших мл. 18 = {sp_fare_mean:.2f}\nКол-во таких пассажиров: {sp_count:.2f}")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C

Средняя стоимость билета выживших мл. 18 = 34.86
Кол-во таких пассажиров: 61.00

**ЗАДАНИЕ 7**

In [70]:
class_g = titanic.groupby('Pclass')
apfagg_g = class_g.agg(
    Mean_Age = ("Age", "mean"),
    Passenger_Count = ("PassengerId", "count"),
    Fare_Mean = ("Fare", "mean")
)
sort_g = apfagg_g.sort_values(by="Fare_Mean",ascending=True)
display(sort_g)

         Mean_Age  Passenger_Count  Fare_Mean
Pclass
3       25.140620              491  13.675550
2       29.877630              184  20.662183
1       38.233441              216  84.154687

**ЗАДАНИЕ 8**

In [71]:
titanic_table = titanic.pivot_table(values='Survived',
 index='Pclass',
 columns='Sex')
display(titanic_table)

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

**ЗАДАНИЕ 9**

In [89]:

null_counts = titanic.isnull().sum()
null_percentages = (titanic.isnull().sum() / len(titanic) * 100).round(2)
sum_table = pd.DataFrame({
    'Null_Count': null_counts,
    'Null_%': null_percentages
})
display(sum_table)
print(f"\n\n{60*'*='}\n\n")
display(titanic.Embarked.value_counts())
titanic['Embarked'] = titanic['Embarked'].fillna('S')
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].mean())
print(f"\n\n{60*'*='}\n\n")
passg_dup = titanic.duplicated(subset=['PassengerId']).sum()
print(f"Количество дубликатов в PassengerId: {passg_dup}")

#Я хз зачем это делать если дубликатов нет, но раз в задании сказано удалить то я это делаю
titanic = titanic.drop_duplicates(subset=['PassengerId'], keep='first')

             Null_Count  Null_%
PassengerId           0     0.0
Survived              0     0.0
Pclass                0     0.0
Name                  0     0.0
Sex                   0     0.0
Age                   0     0.0
SibSp                 0     0.0
Parch                 0     0.0
Ticket                0     0.0
Fare                  0     0.0
Cabin               687    77.1
Embarked              0     0.0
FamilySize            0     0.0

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=


Количество дубликатов в PassengerId: 0

**ЗАДАНИЕ 10**

In [104]:
titanic['FamilySize'] = titanic['SibSp'] + titanic['Parch'] + 1
titanic['IsAlone'] = titanic['FamilySize'].apply(lambda x: 1 if x == 1 else 0)
titanic['AgeGroup'] = pd.cut(titanic['Age'],
 bins=[0, 12, 18, 35, 60, 100],
labels=['ребёнок', 'подросток', 'молодой', 'взрослый',
'пожилой'])
display(titanic[['FamilySize', 'IsAlone', 'Age', 'AgeGroup']])
print(f"\n\n{60*'*='}\n\n")
age_group = titanic.pivot_table(
    values=['Survived', 'Fare', 'PassengerId'],
    index='AgeGroup',
    aggfunc={"Survived":"mean", "Fare":"mean", "PassengerId":"count"}
)
display(age_group)

     FamilySize  IsAlone        Age  AgeGroup
0             2        0  22.000000   молодой
1             2        0  38.000000  взрослый
2             1        1  26.000000   молодой
3             2        0  35.000000   молодой
4             1        1  35.000000   молодой
..          ...      ...        ...       ...
886           1        1  27.000000   молодой
887           1        1  19.000000   молодой
888           4        0  29.699118   молодой
889           1        1  26.000000   молодой
890           1        1  32.000000   молодой

[891 rows x 4 columns]

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

/tmp/ipykernel_3216/3858403002.py:9: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  age_group = titanic.pivot_table(

                Fare  PassengerId  Survived
AgeGroup
ребёнок    31.536352           69  0.579710
подросток  33.451313           70  0.428571
молодой    27.356166          535  0.353271
взрослый   44.259658          195  0.400000
пожилой    41.371214           22  0.227273

**ЗАДАНИЕ 11**

In [111]:
display(titanic.Embarked.value_counts())
print(f"\n\n{60*'*='}\n\n")
emb_group = titanic.groupby("Embarked").agg(
    Age_Mean = ("Age", "mean"),
    Fare_Mean = ("Fare", "mean"),
    Survived_Mean = ("Survived", "mean"),
    First_Class = ("Pclass", lambda x: (x == 1).mean())
)
display(emb_group)

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

           Age_Mean  Fare_Mean  Survived_Mean  First_Class
Embarked
C         30.562419  59.954144       0.553571     0.505952
Q         29.113724  13.276030       0.389610     0.025974
S         29.544382  27.243651       0.339009     0.199690

**ЗАДАНИЕ 12**

In [128]:
fam_group = titanic.groupby("FamilySize").agg(
    Survived_Mean = ("Survived", "mean"),
    Age_Mean = ("Age", "mean"),
    Fare_Mean = ("Fare", "mean"),
    Passenger_Count = ("PassengerId", "count")
)
#Из задания я не сильно понял, нужно оставить только семьи где больше 10 ч или наоборот их убрать
#Поэтому сделаю оба варианта
famm_group = fam_group[fam_group.index < 10]
fam_sort = famm_group.sort_values(by="Survived_Mean")
display(fam_sort)
print(f"\n\n{60*'*='}\n\n")
famn_group = fam_group[fam_group.index > 10]
fam_sort = famn_group.sort_values(by="Survived_Mean")
display(fam_sort)

            Survived_Mean   Age_Mean  Fare_Mean  Passenger_Count
FamilySize
8                0.000000  15.666667  46.900000                6
6                0.136364  18.409091  73.722727               22
5                0.200000  23.186431  58.094453               15
1                0.303538  31.595871  21.242689              537
7                0.333333  15.166667  29.366667               12
2                0.552795  31.160252  49.894129              161
3                0.578431  26.359040  39.692482              102
4                0.724138  19.062698  54.864510               29

*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

            Survived_Mean   Age_Mean  Fare_Mean  Passenger_Count
FamilySize
11                    0.0  29.699118      69.55                7